services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.lukasvanderspiegel.be`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=myresolver"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - proxy
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  default:
    name: jenkins
  proxy:
    external: true
    name: traefik

volumes:
  jenkins-data: